/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "Api": import("@cloudflare/workers-types").Service
    "AuthApi": import("@cloudflare/workers-types").Service
    "Database": import("@cloudflare/workers-types").D1Database
    "JwtSigningSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "PasswordPepper": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "RefreshTokenSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ResendApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Web": {
      "type": "sst.cloudflare.Astro"
      "url": string
    }
  }
}

import "sst"
export {}
