/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "Api": {
      "type": "sst.cloudflare.Worker"
      "url": string
    }
    "AuthApi": {
      "type": "sst.cloudflare.Worker"
      "url": string
    }
    "Database": {
      "databaseId": string
      "type": "sst.cloudflare.D1"
    }
    "Web": {
      "type": "sst.cloudflare.Astro"
      "url": string
    }
  }
}

import "sst"
export {}